/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baeldung_jni_shared_mem */

#ifndef _Included_com_baeldung_jni_shared_mem
#define _Included_com_baeldung_jni_shared_mem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baeldung_jni_shared_mem
 * Method:    add
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_baeldung_jni_shared_mem_add
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
