/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdint.h>
/* Header for class sharedMem */

#ifndef _Included_sharedMem
#define _Included_sharedMem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sharedMem
 * Method:    add
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sharedMem_add
  (JNIEnv* env, jobject, jint pos, jstring data);

JNIEXPORT string JNICALL Java_sharedMem_get
  (JNIEnv* env, jobject, jint pos);

JNIEXPORT bool JNICALL Java_sharedMem_create
  (JNIEnv* env, jobject, jint numChar, jint arrayLength);

#ifdef __cplusplus
}
#endif
#endif
