/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdint.h>
/* Header for class sharedMem */

#ifndef _Included_sharedMem
#define _Included_sharedMem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sharedMem
 * Method:    add
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sharedMem_add
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
